import productModel from '../models/productModel.js';

const baseUrl = process.env.PRODUCT_ASSET_BASE_URL || 'http://localhost:5175/src/assets';

const restoredProducts = [
  {
    name: 'Women Round Neck Cotton Top',
    description: 'Clean everyday women top with a soft rounded neckline and comfortable cotton fit.',
    price: 100,
    image: [`${baseUrl}/p_img5.png`],
    category: 'Women',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L'],
    bestseller: true,
    date: Date.now() - 1000 * 60 * 60 * 24 * 12,
  },
  {
    name: 'Girls Round Neck Cotton Top',
    description: 'Bright, cheerful kids top designed for a relaxed and playful everyday look.',
    price: 110,
    image: [`${baseUrl}/p_img6.png`],
    category: 'Kids',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L'],
    bestseller: true,
    date: Date.now() - 1000 * 60 * 60 * 24 * 11,
  },
  {
    name: 'Men Round Neck Pure Cotton T-shirt',
    description: 'Classic premium cotton t-shirt with a clean fit and everyday versatility.',
    price: 120,
    image: [`${baseUrl}/p_img1.png`],
    category: 'Men',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: true,
    date: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
  {
    name: 'Men Tapered Fit Flat-Front Trousers',
    description: 'Smart, tailored trousers with a clean drape and comfortable everyday structure.',
    price: 150,
    image: [`${baseUrl}/p_img7.png`],
    category: 'Men',
    subCategory: 'Bottomwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 24 * 9,
  },
  {
    name: 'Women Palazzo Pants with Waist Belt',
    description: 'Elegant wide-leg women pants with graceful movement and a flattering fit.',
    price: 190,
    image: [`${baseUrl}/p_img20.png`],
    category: 'Women',
    subCategory: 'Bottomwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: true,
    date: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
  {
    name: 'Women Zip-Front Relaxed Fit Jacket',
    description: 'A comfortable outer layer with a modern zip-front fit and polished women silhouette.',
    price: 210,
    image: [`${baseUrl}/p_img21.png`],
    category: 'Women',
    subCategory: 'Winterwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: true,
    date: Date.now() - 1000 * 60 * 60 * 24 * 7,
  },
  {
    name: 'Men Slim Fit Relaxed Denim Jacket',
    description: 'Structured denim look for versatile layering with a modern relaxed fit.',
    price: 220,
    image: [`${baseUrl}/p_img52.png`],
    category: 'Men',
    subCategory: 'Winterwear',
    sizes: ['S', 'M', 'L'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    name: 'Boy Round Neck Pure Cotton T-shirt',
    description: 'Soft comfort-focused tee for everyday wear and easy movement.',
    price: 90,
    image: [`${baseUrl}/p_img3.png`],
    category: 'Kids',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    name: 'Kid Tapered Slim Fit Trouser',
    description: 'Simple and smart slim trouser for daily comfort and a polished silhouette.',
    price: 95,
    image: [`${baseUrl}/p_img49.png`],
    category: 'Kids',
    subCategory: 'Bottomwear',
    sizes: ['S', 'M', 'L'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    name: 'Women Printed Palazzo Pants',
    description: 'Statement bottomwear with a printed finish and flowy drape for effortless styling.',
    price: 180,
    image: [`${baseUrl}/p_img22.png`],
    category: 'Women',
    subCategory: 'Bottomwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    name: 'Women Zip-Front Relaxed Fit Jacket',
    description: 'A polished winter layer designed for all-day comfort and easy layering.',
    price: 240,
    image: [`${baseUrl}/p_img26.png`],
    category: 'Women',
    subCategory: 'Winterwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    name: 'Women Round Neck Cotton Top',
    description: 'A premium cotton top for a neat, relaxed everyday look with soft texture.',
    price: 130,
    image: [`${baseUrl}/p_img29.png`],
    category: 'Women',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: true,
    date: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    name: 'Women Round Neck Cotton Top',
    description: 'Fresh, easy-fit women top built for comfort, movement, and everyday style.',
    price: 140,
    image: [`${baseUrl}/p_img34.png`],
    category: 'Women',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 22,
  },
  {
    name: 'Women Zip-Front Relaxed Fit Jacket',
    description: 'Structured women winterwear with subtle premium styling and refined layering.',
    price: 250,
    image: [`${baseUrl}/p_img35.png`],
    category: 'Women',
    subCategory: 'Winterwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 20,
  },
  {
    name: 'Women Round Neck Cotton Top',
    description: 'Soft cotton women top with a simple shape and easy-to-style silhouette.',
    price: 160,
    image: [`${baseUrl}/p_img37.png`],
    category: 'Women',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 18,
  },
  {
    name: 'Women Zip-Front Relaxed Fit Jacket',
    description: 'A season-ready jacket designed for elegant women styling and easy layering.',
    price: 260,
    image: [`${baseUrl}/p_img44.png`],
    category: 'Women',
    subCategory: 'Winterwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 16,
  },
  {
    name: 'Men Printed Plain Cotton Shirt',
    description: 'Modern men shirt with a refined printed detail and structured fit.',
    price: 170,
    image: [`${baseUrl}/p_img39.png`],
    category: 'Men',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 15,
  },
  {
    name: 'Men Round Neck Pure Cotton T-shirt',
    description: 'A premium everyday tee designed with clean styling and soft cotton comfort.',
    price: 180,
    image: [`${baseUrl}/p_img41.png`],
    category: 'Men',
    subCategory: 'Topwear',
    sizes: ['S', 'M', 'L', 'XL'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 14,
  },
  {
    name: 'Kid Tapered Slim Fit Trouser',
    description: 'Easy-fit kids trouser offering comfort and polished styling for everyday use.',
    price: 130,
    image: [`${baseUrl}/p_img47.png`],
    category: 'Kids',
    subCategory: 'Bottomwear',
    sizes: ['S', 'M', 'L'],
    bestseller: false,
    date: Date.now() - 1000 * 60 * 60 * 12,
  },
];

const seedProducts = async () => {
  try {
    const existingProducts = await productModel.countDocuments();
    if (existingProducts > 0) {
      console.log(`Product catalog already contains ${existingProducts} items`);
      return;
    }
    await productModel.insertMany(restoredProducts);
    console.log(`Restored product catalog seeded: ${restoredProducts.length} items`);
  } catch (error) {
    console.error('Failed to restore product catalog:', error.message);
  }
};

export default seedProducts;
